name: Deploy to Hetzner

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: deploy-eezycourt
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (metadata only)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Trust server host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Run deploy script on server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          DEPLOY_CMD: ${{ secrets.DEPLOY_CMD }}
        run: |
          ssh ${SSH_USER}@${SSH_HOST} "${DEPLOY_CMD}"

      - name: Health check
        run: |
          echo "Waiting for server to start..."
          sleep 10

          # Retry health check up to 5 times with 5 second delays
          for i in {1..5}; do
            echo "Health check attempt $i/5..."
            if curl -fsS https://eezycourt.services/healthz; then
              echo "✅ Health check passed!"
              exit 0
            fi
            if [ $i -lt 5 ]; then
              echo "⏳ Retrying in 5 seconds..."
              sleep 5
            fi
          done

          echo "❌ Health check failed after 5 attempts"
          exit 1
